# pre-commit install
# pre-commit run --all-files
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  # * Top level
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        exclude: ^uv[.]lock
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
  # * Sync dependencies
  - repo: https://github.com/mxr/sync-pre-commit-deps
    rev: v0.0.3
    hooks:
      - id: sync-pre-commit-deps

  # * Pyproject-fmt
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.5.0
    hooks:
      - id: pyproject-fmt
        args: [--indent=4, --keep-full-version]
        files: ""
        types: [toml]
        exclude: ^tests/data

  # * Prettier
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.4.2
    hooks:
      - id: prettier
        alias: markdownlint
        stages: [pre-commit]

  # * Markdown
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.17.2
    hooks:
      - id: markdownlint-cli2
        alias: markdownlint
        args: [--style, prettier]
        # language_version: 10.9.0

  # * Linting
  # To be replace by ruff analog when I find one ...
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.19.1
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==24.10.0
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      - id: ruff
        alias: ruff-all
        types_or: &ruff-types-or [python, pyi, jupyter]
        args: [--fix, --show-fixes]
      - id: ruff-format
        alias: ruff-all
        types_or: *ruff-types-or

  # * Spelling
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.0
    hooks:
      - id: codespell
        additional_dependencies: [tomli]
        args: [-I, docs/spelling_wordlist.txt]
        exclude_types: [jupyter]
        exclude: ^uv[.]lock$|^requirements

  # * Commit message
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # * uv
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.5.22
    hooks:
      - id: uv-lock
        args: [--locked]

  # * Manual Linting ------------------------------------------------------------
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        stages: [manual]
        args: [--py38-plus]

  # ** typos
  # Probably stick with codespell, but this might also be nice...
  - repo: https://github.com/crate-ci/typos
    rev: dictgen-v0.3.1
    hooks:
      - id: typos
        stages: [manual]
        exclude: "[.]ipynb$|^uv[.]lock$|^requirements"
