# pre-commit install
# pre-commit run --all-files
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  # * Top level
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        exclude: ^uv[.]lock
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending

  # * pyproject.toml
  # ** format
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.5.1
    hooks:
      - id: pyproject-fmt
        args: [--indent=4, --keep-full-version]
        files: ""
        types: [toml]
        exclude: ^tests/data
  # ** validate
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
  # ** validate (schema-store)
  - repo: https://github.com/henryiii/validate-pyproject-schema-store
    rev: 2025.03.24
    hooks:
      - id: validate-pyproject
        alias: validate-pyproject-full
        stages: [manual]

  # * Prettier
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.5.3
    hooks:
      - id: prettier
        alias: markdownlint
        stages: [pre-commit, manual]

  # * Markdown
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.17.2
    hooks:
      - id: markdownlint-cli2
        alias: markdownlint
        args: [--style, prettier]
        # language_version: 10.9.0

  # * Linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        alias: ruff-all
        types_or: &ruff-types-or [python, pyi, jupyter]
        args: [--fix, --show-fixes]
      - id: ruff-format
        alias: ruff-all
        types_or: *ruff-types-or
  # To be replace by ruff analog when I find one ...
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.19.1
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==25.1.0

  # * Spelling
  # ** typos (only with manual)
  - repo: https://github.com/crate-ci/typos
    rev: v1.30.3
    hooks:
      - id: typos
        stages: [manual]
        exclude_types: [jupyter]
        exclude: ^uv[.]lock$|^requirements
  # ** codespell
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies: [tomli]
        args: [-I, docs/spelling_wordlist.txt]
        exclude_types: [jupyter]
        exclude: ^uv[.]lock$|^requirements

  # * Dependencies
  # ** uv
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.9
    hooks:
      - id: uv-lock
        args: [--locked]
  # ** pyproject2conda
  - repo: https://github.com/usnistgov/pyproject2conda
    rev: v0.19.1
    hooks:
      - id: pyproject2conda-project
        alias: requirements
  # ** all lock files
  - repo: local
    hooks:
      - id: requirements-lock
        name: requirements-lock
        alias: lock
        entry: nox -s lock -- # ++lock-force
        language: python
        files: ^requirements/.*\.txt$
        pass_filenames: false
        additional_dependencies: ["nox==2025.2.9"]

  # * Commit message
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.4.1
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # * Makefile
  - repo: https://github.com/mrtazz/checkmake.git
    rev: 0.2.2
    hooks:
      - id: checkmake
        stages: [manual]
