# mypy: disable-error-code="no-untyped-def, no-untyped-call"
# pylint: disable=duplicate-code,empty-comment
from __future__ import annotations

import locale
import tempfile
from textwrap import dedent

import pytest
from pydantic import ValidationError

from pyproject2conda import requirements
from pyproject2conda._config import PyProject2CondaConfig


def test_header() -> None:
    from pyproject2conda.requirements import _create_header

    expected = dedent(
        """\
#
# This file is autogenerated by pyproject2conda.
# You should not manually edit this file.
# Instead edit the corresponding pyproject.toml file.
#"""
    )

    assert expected == _create_header()

    cmd = "hello"
    out = _create_header(cmd=cmd)

    header = dedent(
        f"""\
#
# This file is autogenerated by pyproject2conda
# with the following command:
#
#     $ {cmd}
#
# You should not manually edit this file.
# Instead edit the corresponding pyproject.toml file.
#"""
    )

    assert out == header


def test_optional_write() -> None:
    from pathlib import Path

    from pyproject2conda.requirements import _optional_write

    s = "hello"
    with tempfile.TemporaryDirectory() as d:
        p = Path(d) / "tmp.txt"

        _optional_write(s, p)

        test = Path(p).read_text(encoding=locale.getpreferredencoding(False))

        assert test == s


def test_output_to_yaml() -> None:
    from pyproject2conda.requirements import _conda_yaml

    with pytest.raises(ValueError):
        s = _conda_yaml()

    s = _conda_yaml(
        conda_deps=["a", "pip"],
        channels=["conda-forge"],
        pip_deps=["pip-thing"],
        name="hello",
    )

    expected = """\
name: hello
channels:
  - conda-forge
dependencies:
  - a
  - pip
  - pip:
      - pip-thing
    """

    assert s == dedent(expected)


def test_infer() -> None:
    toml = dedent(
        """\
    [project]
    name = "hello"
    dependencies = [
    "athing",
    "bthing",
    "cthing; python_version<'3.10'",
    ]

    [project.optional-dependencies]
    test = [
    "pandas",
    "pytest",
    ]
    dev-extras = [
    "matplotlib",
    ]
    dev = [
    "hello[test]",
    "hello[dev-extras]",
    ]
    dist-pypi = [
    "setuptools",
    "build",
    ]


    [tool.pyproject2conda]
    channels = 'conda-forge'

    [tool.pyproject2conda.dependencies]
    athing = { pip = true }
    bthing = { skip = true, packages = "bthing-conda" }
    cthing = { channel = "conda-forge" }
    pytest = { channel = "conda-forge" }
    matplotlib = { skip = true, packages = [
        "additional-thing",
        "conda-matplotlib"
    ] }

    """
    )

    d = requirements.ParseRequirements.from_string(toml)
    with pytest.raises(ValueError):
        d.to_conda_yaml(python_include="infer")


def test_pip_requirements() -> None:
    toml = dedent(
        """\
    [project]
    name="hello"
    requires-python = ">=3.8,<3.11"
    dependencies = [
    "athing",
    "bthing",
    "cthing; python_version<'3.10'",
    ]

    [project.optional-dependencies]
    test = ["pytest", "test-optional"]
    dev = ["hello[test]", "dev-package"]

    [dependency-groups]
    test = ["pytest", "test-optional-group"]
    dev = [{include-group= "test"}, "dev-package-group"]
        """
    )

    expected = dedent(
        """\
    athing
    bthing
    cthing; python_version < "3.10"
    hello
    """
    )

    d = requirements.ParseRequirements.from_string(toml)

    assert d.to_requirements(pip_deps=["hello"]) == expected

    expected = dedent(
        """\
        athing
        bthing
        cthing; python_version < "3.10"
        dev-package
        hello
        pytest
        test-optional
        """
    )

    d = requirements.ParseRequirements.from_string(toml)
    assert d.to_requirements(pip_deps=["hello"], extras="dev") == expected
    assert d.to_requirements(pip_deps=["hello"], extras_or_groups="dev") == expected

    expected = dedent(
        """\
        athing
        bthing
        cthing; python_version < "3.10"
        dev-package-group
        hello
        pytest
        test-optional-group
        """
    )

    d = requirements.ParseRequirements.from_string(toml)
    assert d.to_requirements(pip_deps="hello", groups="dev") == expected

    # build-system.requires


def test_to_conda_requirements_error() -> None:
    toml = dedent(
        """\
    [project]
    requires-python = ">=3.8,<3.11"
    dependencies = [
    "athing",
    "bthing",
    "cthing; python_version<'3.10'",
    ]

    [tool.pyproject2conda.dependencies]
    athing = { pip = true }
    bthing = { skip = true, packages = "bthing-conda" }
    cthing = { channel = "conda-forge" }
        """
    )

    with pytest.raises(ValidationError):
        requirements.ParseRequirements.from_string(toml)


def test_package_name() -> None:
    toml = dedent(
        """\
    [project]
    requires-python = ">=3.8,<3.11"
    dependencies = [
    "athing",
    "bthing",
    "cthing; python_version<'3.10'",
    ]

    [project.optional-dependencies]
    test = [
    "pandas",
    "pytest",
    ]
    dev-extras = [
    "matplotlib",
    ]
    dev = [
    "hello[test]",
    "hello[dev-extras]",
    ]
    dist-pypi = [
    "setuptools",
    "build",
    ]


    [tool.pyproject2conda]
    channels = ['conda-forge']

    [tool.pyproject2conda.dependencies]
    athing = { pip = true }
    bthing = { skip = true, packages = "bthing-conda" }
    cthing = { channel = "conda-forge" }
    pytest = { channel = "conda-forge" }
    matplotlib = { skip = true, packages = [
        "additional-thing",
        "conda-matplotlib"
    ] }
    """
    )
    with pytest.raises(ValidationError):
        requirements.ParseRequirements.from_string(toml)


def test_conda_and_pip_simple() -> None:
    toml = dedent(
        """\
    [project]
    name = "hello"
    dependencies = [
    "a",
    # thing
    "b",
    ]
        """
    )

    d = requirements.ParseRequirements.from_string(toml)

    conda_deps, pip_deps = requirements.conda_and_pip_reqs_to_list(
        *d.conda_and_pip_requirements()
    )

    assert conda_deps == ["a", "b"]

    assert pip_deps == []


@pytest.mark.parametrize(
    ("style", "toml"),
    [
        # Extras
        (
            "extras",
            dedent(
                """\
                [build-system]
                requires = ["setuptools>=61.2", "setuptools_scm[toml]>=8.0"]
                build-backend = "setuptools.build_meta"

                [project]
                name = "hello"
                requires-python = ">=3.8, <3.11"
                dependencies = [
                "athing",
                "bthing",
                "cthing; python_version<'3.10'",
                ]

                [project.optional-dependencies]
                test = [
                "pandas",
                "pytest",
                ]
                dev-extras = [
                "matplotlib",
                ]
                dev = [
                "hello[test]",
                "hello[dev-extras]",
                ]
                dist-pypi = [
                "setuptools",
                "build",
                ]


                [tool.pyproject2conda]
                channels = ['conda-forge']

                [tool.pyproject2conda.dependencies]
                athing = {pip = true}
                bthing = {skip = true, packages = "bthing-conda"}
                cthing = {channel = "conda-forge"}
                pytest = {channel = "conda-forge"}
                matplotlib = {skip = true, packages = ["additional-thing", "conda-matplotlib"]}
                build = { channel = "pip" }
                """
            ),
        ),
        # Groups
        (
            "groups",
            dedent(
                """\
                [build-system]
                requires = ["setuptools>=61.2", "setuptools_scm[toml]>=8.0"]
                build-backend = "setuptools.build_meta"

                [project]
                name = "hello"
                requires-python = ">=3.8, <3.11"
                dependencies = [
                "athing",
                "bthing",
                "cthing; python_version<'3.10'",
                ]

                [dependency-groups]
                test = [
                "pandas",
                "pytest",
                ]
                dev-extras = [
                "matplotlib",
                ]
                dev = [
                {include-group = "test"},
                {include-group = "dev-extras"},
                ]
                dist-pypi = [
                "setuptools",
                "build",
                ]


                [tool.pyproject2conda]
                channels = ['conda-forge']

                [tool.pyproject2conda.dependencies]
                athing = {pip = true}
                bthing = {skip = true, packages = "bthing-conda"}
                cthing = {channel = "conda-forge"}
                pytest = {channel = "conda-forge"}
                matplotlib = {skip = true, packages = ["additional-thing", "conda-matplotlib"]}
                build = { channel = "pip" }
                """
            ),
        ),
    ],
)
def test_complete(style, toml) -> None:
    d = requirements.ParseRequirements.from_string(toml)
    channels = PyProject2CondaConfig.from_string(toml).get_env(None).channels

    # test unknown extra
    with pytest.raises(KeyError):
        d.to_conda_yaml(extras="a-thing")

    assert set(
        getattr(
            d, "optional_dependencies" if style == "extras" else "dependency_groups"
        ).unresolved
    ) == {
        "test",
        "dev-extras",
        "dev",
        "dist-pypi",
        "build-system-requires",
    }

    # test build-system.requires
    expected = """\
    setuptools-scm[toml]>=8.0
    setuptools>=61.2
    """
    assert dedent(expected) == d.to_requirements(
        skip_package=True,
        # pyrefly: ignore [bad-argument-type]
        **{style: "build-system.requires"},  # type: ignore[arg-type]  # pyright: ignore[reportArgumentType]  # ty:ignore[invalid-argument-type]
    )

    expected = """\
channels:
  - conda-forge
dependencies:
  - bthing-conda
  - conda-forge::cthing
  - pip
  - pip:
      - athing
    """

    assert dedent(expected) == d.to_conda_yaml(channels=channels)

    expected = """\
dependencies:
  - bthing-conda
  - conda-forge::cthing
  - pip
  - pip:
      - -e .
      - athing
    """

    assert dedent(expected) == d.to_conda_yaml(pip_deps="-e .")

    # test -p option
    expected = """\
dependencies:
  - python<3.11,>=3.8
  - bthing-conda
  - conda-forge::cthing
  - pip
  - pip:
      - athing
    """
    assert dedent(expected) == d.to_conda_yaml(python_include="infer")

    # with remove spaces:
    expected = """\
channels:
  - conda-forge
dependencies:
  - python<3.11,>=3.8
  - bthing-conda
  - conda-forge::cthing
  - pip
  - pip:
      - athing
    """
    assert dedent(expected) == d.to_conda_yaml(
        python_include="infer",
        channels=channels,
    )

    expected = """\
dependencies:
  - python=3.9
  - bthing-conda
  - conda-forge::cthing
  - pip
  - pip:
      - athing
    """
    assert dedent(expected) == d.to_conda_yaml(python_include="python~=3.9")

    # test passing python_version
    expected = """\
dependencies:
  - python=3.10
  - bthing-conda
  - pip
  - pip:
      - athing
    """
    assert dedent(expected) == d.to_conda_yaml(
        python_include="python~=3.10", python_version="3.10"
    )

    out = d.to_conda_yaml(channels="hello")

    expected = """\
channels:
  - hello
dependencies:
  - bthing-conda
  - conda-forge::cthing
  - pip
  - pip:
      - athing
    """

    assert dedent(expected) == out

    # pyrefly: ignore [bad-argument-type]
    out = d.to_conda_yaml(**{style: "test"})  # type: ignore[arg-type]  # pyright: ignore[reportArgumentType]  # ty:ignore[invalid-argument-type]

    expected = """\
dependencies:
  - bthing-conda
  - conda-forge::cthing
  - conda-forge::pytest
  - pandas
  - pip
  - pip:
      - athing
    """

    assert dedent(expected) == out

    # pyrefly: ignore [bad-argument-type]
    out = d.to_conda_yaml(**{style: "dist-pypi"}, skip_package=True)  # type: ignore[arg-type]  # pyright: ignore[reportArgumentType]  # ty:ignore[invalid-argument-type]

    expected = """\
dependencies:
  - setuptools
  - pip
  - pip:
      - build
    """

    assert out == dedent(expected)

    expected = """\
channels:
  - conda-forge
dependencies:
  - additional-thing
  - bthing-conda
  - conda-forge::cthing
  - conda-forge::pytest
  - conda-matplotlib
  - pandas
  - pip
  - pip:
      - athing
    """

    # pyrefly: ignore [bad-argument-type]
    assert dedent(expected) == d.to_conda_yaml(**{style: "dev"}, channels=channels)  # type: ignore[arg-type]  # pyright: ignore[reportArgumentType]  # ty:ignore[invalid-argument-type]

    # Test deps/reqs
    expected = """\
dependencies:
  - bthing-conda
  - conda-forge::cthing
  - dep
  - pip
  - pip:
      - athing
      - req
    """

    assert dedent(expected) == d.to_conda_yaml(
        conda_deps="dep;python_version<'3.10'", pip_deps=["req"]
    )

    expected = """\
dependencies:
  - python=3.10
  - bthing-conda
  - pip
  - pip:
      - athing
      - req; python_version < "3.10"
    """
    assert dedent(expected) == d.to_conda_yaml(
        conda_deps=["dep;python_version<'3.10'"],
        pip_deps=["req;python_version<'3.10'"],
        python_include="python~=3.10",
        python_version="3.10",
    )


def test_missing_dependencies() -> None:
    toml = dedent(
        """\
    [project]
    name = "hello"
    requires-python = ">=3.8,<3.11"
    dependencies = []

    [project.optional-dependencies]
    test = [
    "pandas",
    "pytest",
    "pytest-accept",
    ]
    dev-extras = [

    "matplotlib",
    ]
    dev = [
    "hello[test]",
    "hello[dev-extras]",
    ]

    [tool.pyproject2conda]
    channels = ['conda-forge']

    [tool.pyproject2conda.dependencies]
    pytest = { channel = "conda-forge" }
    pytest-accept = { pip = true }
    matplotlib = { skip = true, packages = [
        "additional-thing",
        "conda-matplotlib"
    ] }
    """
    )

    d = requirements.ParseRequirements.from_string(toml)

    expected = """\
dependencies:
  - conda-forge::pytest
  - pandas
  - pip
  - pip:
      - pytest-accept
    """

    assert dedent(expected) == d.to_conda_yaml(
        extras="test",
        skip_package=True,
    )

    toml = dedent(
        """\
    [project]
    name = "hello"
    requires-python = ">=3.8,<3.11"

    [project.optional-dependencies]
    test = [
    "pandas",
    "pytest",
    "pytest-accept",
    ]
    dev-extras = [

    "matplotlib",
    ]
    dev = [
    "hello[test]",
    "hello[dev-extras]",
    ]

    [tool.pyproject2conda]
    channels = ['conda-forge']

    [tool.pyproject2conda.dependencies]
    pytest = { channel = "conda-forge" }
    pytest-accept = { pip = true }
    matplotlib = { skip = true, packages = [
        "additional-thing",
        "conda-matplotlib"
    ] }
    """
    )

    d = requirements.ParseRequirements.from_string(toml)

    assert dedent(expected) == d.to_conda_yaml(
        extras="test",
        skip_package=True,
    )

    assert dedent(expected) == d.to_conda_yaml(
        extras="test",
        skip_package=False,
    )

    # check output has no dependencies:
    for attr in ("to_conda_yaml", "to_requirements"):
        f = getattr(d, attr)
        with pytest.raises(ValueError):
            f()

        assert f(allow_empty=True) == "No dependencies for this environment\n"


def test_clean_conda() -> None:
    toml = dedent(
        """\
    [project]
    name = "hello"
    requires-python = ">=3.8,<3.11"

    [project.optional-dependencies]
    test = [
    "pandas",
    "pytest",
    "pytest-accept",
    ]
    dev-extras = [

    "matplotlib",
    ]
    dev = [
    "hello[test]",
    "hello[dev-extras]",
    ]

    [tool.pyproject2conda]
    channels = ['conda-forge']


    [tool.pyproject2conda.dependencies]
    pytest = { channel = "conda-forge" }
    pytest-accept = { pip = true }
    matplotlib = { skip = true, packages = [
        "additional-thing",
        "conda-forge::conda-matplotlib"
    ] }
    """
    )

    expected = """\
dependencies:
  - additional-thing
  - conda-forge::conda-matplotlib
    """

    d = requirements.ParseRequirements.from_string(toml)

    assert dedent(expected) == d.to_conda_yaml(
        extras="dev-extras",
        skip_package=True,
    )


def test_no_optional_deps() -> None:
    toml = dedent(
        """\
    [project]
    name = "hello"
    requires-python = ">=3.8,<3.11"
    dependencies = [
    "athing >0.5",
    "bthing > 1.0",
    "cthing; python_version < '3.10'",
    ]

    [tool.pyproject2conda]
    channels = ['conda-forge']

    [tool.pyproject2conda.dependencies]
    athing = { pip = true }
    bthing = { skip = true, packages = "bthing-conda > 2.0" }
    cthing = { channel = "conda-forge" }
    """
    )

    expected = """\
dependencies:
  - python<3.11,>=3.8
  - bthing-conda>2.0
  - conda-forge::cthing
  - pip
  - pip:
      - athing>0.5
    """

    d = requirements.ParseRequirements.from_string(toml)

    assert d.optional_dependencies.unresolved == {}

    assert dedent(expected) == d.to_conda_yaml(python_include="infer")


@pytest.mark.parametrize(
    "toml",
    [
        dedent(
            """\
            [project]
            name = "hello"
            requires-python = ">=3.8, <3.11"
            dependencies = [
            "athing >0.5",
            "bthing > 1.0",
            "cthing; python_version < '3.10'",
            ]


            [tool.pyproject2conda]
            channels = ['conda-forge']

            [tool.pyproject2conda.dependencies]
            athing = {pip = true}
            bthing = {skip = true, packages = "bthing-conda > 2.0"}
            cthing = {channel = "conda-forge"}
            """
        ),
    ],
)
def test_spaces(toml) -> None:
    d = requirements.ParseRequirements.from_string(toml)

    expected = """\
dependencies:
  - python<3.11,>=3.8
  - bthing-conda>2.0
  - conda-forge::cthing
  - pip
  - pip:
      - athing>0.5
    """
    assert dedent(expected) == d.to_conda_yaml(
        python_include="infer",
    )

    expected = """\
dependencies:
  - python<3.11,>=3.8
  - bthing-conda>2.0
  - conda-forge::cthing
  - pip
  - pip:
      - athing>0.5
    """
    assert dedent(expected) == d.to_conda_yaml(
        python_include="infer",
    )

    expected = """\
    athing>0.5
    bthing>1.0
    cthing; python_version < "3.10"
    """

    assert dedent(expected) == d.to_requirements()


def test_include_pip() -> None:
    toml = dedent(
        """\
        [build-system]
        requires = ["setuptools>=61.2", "setuptools_scm[toml]>=8.0"]
        build-backend = "setuptools.build_meta"

        [project]
        name = "hello"
        requires-python = ">=3.8, <3.11"
        dependencies = [
        "athing",
        ]

        [project.optional-dependencies]
        test = [
        "xthing",
        ]
        """
    )

    expected = """\
    dependencies:
      - athing
      - xthing
      - pip
    """

    d = requirements.ParseRequirements.from_string(toml)

    assert dedent(expected) == d.to_conda_yaml(extras="test", conda_deps="pip")
