test:
  imports:
    - pyproject2conda
  commands:
    - pip check
    - pyproject2conda --help
    - p2c --help
  requires:
    - pip

about:
  home: https://github.com/usnistgov/pyproject2conda
  summary:
    A script to convert a Python project declared on a pyproject.toml to a conda
    environment.
  description: |
    A script to convert a Python project declared on a pyproject.toml to a conda environment.
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
